type User {
    name: String
    identity: Identity!
    boards: [Board!]! @relation
    assignments: [Assignment!] @unique
    classes: [Class!] @unique
    projects: [Project!] @unqiue
}

type Class {
    name: String!
    color: String
    classBoard: Board  
    owner: User! 
    # endsAt: Time
}

type Assignment {
    name: String!
    desc: String
    dueDate: Time
    relatedClass: Class  
    owner: User!  
    parentTaskList: TaskList @relation
}

type Project {
    name: String!
    desc: String
    board: Board  
    owner: User!  
}

type Board {
    name: String!
    list: [TaskList!] @unqiue
    owner: User! @relation
}

type TaskList {
    name: String!
    assignments: [Assignment!] @relation @unique
    owner: User!  
    board: Board  
}

type Identity {
    googleId: ID! @unique
    email: String!
    createdAt: Time!
    updatedAt: Time!
    confirmationSentAt: Time!
}
