type Planner {
# List of boards
}

type Class {
# Name
# List of Assignments
}

type Assignment {
# due date
# name
# related class
}

# A group of related assignments.
type Project 
 {
# Name
# Board
}

type Board {
# List of assignments
}

type List {
# Typeof - To Do/Doing/Done
# Assignments
}

type User {
# Name
# Identity information
# Board
# Assignments
# Classes
}

